
/* 1 */
CREATE OR REPLACE TRIGGER affichage
AFTER INSERT OR DELETE OR UPDATE 
ON INFIRMIER 
BEGIN 
	IF(INSERTING) THEN 
		DBMS_OUTPUT.put_line('INFIRMIER INSERE');
	END IF;	
	IF (DELETING) THEN	
		DBMS_OUTPUT.put_line('INFIRMIER SUPPRIME');
	END IF;
	IF (UPDATING) THEN	
		DBMS_OUTPUT.put_line('INFIRMIER MISE A JOUR');
	END IF;
END;
/	

/* 2 */

CREATE OR REPLACE TRIGGER nv_inf_affecte
AFTER INSERT  
ON INFIRMIER 
FOR EACH ROW
BEGIN 
	DBMS_OUTPUT.put_line('UN NOUVEAU EMPLOYE EST AFFECTE A '
	||:NEW.CODE_SERVICE);
END;
/

/* 3 */
CREATE OR REPLACE TRIGGER verif_code_service
BEFORE UPDATE  
ON INFIRMIER 
FOR EACH ROW
DECLARE
	N INTEGER; 
BEGIN 
	SELECT COUNT(*) INTO N
	FROM SERVICE S
	WHERE S.CODE_SERVICE = :NEW.CODE_SERVICE;
	
	IF( N = 0) THEN
		RAISE_APPLICATION_ERROR(-20555, 'CODE SERVICE NON VALIDE !');
	END IF;
END;
/